# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  main@v1:
    root: openapi/openapi.yaml

extends:
  - recommended
rules:
  no-unused-components: warn

theme:
  openapi:
    pagination: section
