name: build-doc
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build API Specification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Bundle
        run: npm run bundle
      - name: Copy favicon to dist
        run: cp docs/favicon.png dist
      - name: Copy favicon to dist
        run: cp docs/favicon.png dist
      - name: Build HTML file
        run: npm run doc
      - name: Deploy on Github pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}