name: build-doc
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build API Specification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Bundle
        run: npm run bundle
      - name: Deploy on gh-pages
        run: npm run deploy-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}